### ISSUE TITLE
Add new widget css to app.css

### ISSUE THREAD

**Issue by steveoh** [steveoh/generator-dojo-widget#9]
It is a pain to have to remember to import new widget css to the app.css. Add a new boolean option to ask to add it to app.css.

**Comment by stdavis** [comment]
Not needed if using xstyle to load widget css. 



—

**Comment by steveoh** [comment]
have we moved past the bugs in xstyle yet?

https://github.com/steveoh/generator-dojo-widget/pull/8 is waiting and I
thought it had a comment to wait, but that must be somewhere else.

**Comment by stdavis** [comment]
I think that there might be a few bugs left but it's working well enough for me to use in production. I think that it's good enough to start using. 



—

**Comment by stdavis** [comment]
I think that we are past this issue and that it could be closed

https://github.com/steveoh/generator-dojo-widget/blob/master/app/templates/_widget.js#L11

**Comment by steveoh** [comment]
yes, i think you are right. It would be nice to do this for the agrc.widgets library to remove the need for manual css inclusion.
